name: manual

on:
    workflow_dispatch:

jobs:
    my_job: 
        runs-on: ubuntu-latest
        steps:
            - name: check out code
              uses: actions/checkout@v4
            
            - name: run somthing ...
              run: |
                echo "Hello from GITHUB!"
